# Generated by Django 5.2 on 2025-04-20 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='SaveToFavorite',
        ),
        migrations.CreateModel(
            name='FavoriteMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
                ('save_to_favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.savetofavorite')),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteMovie',
        ),
    ]
