# Generated by Django 5.2 on 2025-04-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_rename_favorite_savetofavorite_favoritemovies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='movie_dubbing_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='movie_dubbing_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
