# Generated by Django 5.2 on 2025-04-20 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_actor_age_alter_director_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
